FROM balenalib/%%BALENA_MACHINE_NAME%%-node:14-buster-build

RUN install_packages git

WORKDIR /usr/src/app

COPY . ./

# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1
